apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
  labels: { app: minio }
spec:
  replicas: 1
  selector: { matchLabels: { app: minio } }
  template:
    metadata:
      labels: { app: minio }
    spec:
      nodeSelector:
        kubernetes.io/hostname: debian   # только на worker
      containers:
      - name: minio
        image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
        args: ["server", "/data", "--console-address=:9001"]
        envFrom:
        - secretRef:
            name: minio-root
        env:
        - name: MINIO_BROWSER
          value: "on"
        - name: MINIO_REGION
          value: "us-east-1"
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: "public"
        - name: MINIO_SERVER_URL
          value: "https://minio.pufferfish.ru"
        ports:
        - { name: api,     containerPort: 9000 }
        - { name: console, containerPort: 9001 }
        readinessProbe:
          httpGet: { path: /minio/health/ready, port: 9000 }
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /minio/health/live, port: 9000 }
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests: { cpu: "100m", memory: "256Mi" }
          limits:   { cpu: "500m", memory: "1Gi" }
        volumeMounts:
        - { name: data, mountPath: /data }
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-data