replicaCount: 1
mode: standalone

# Use CPU-v1 compatible images (older CPUs)
image:
  repository: minio/minio
  tag: RELEASE.2024-12-18T13-15-44Z-cpuv1
  pullPolicy: IfNotPresent

mcImage:
  repository: minio/mc
  tag: RELEASE.2024-11-21T17-21-54Z-cpuv1
  pullPolicy: IfNotPresent

auth:
  rootUser: ""
  rootPassword: ""

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 250m

consoleIngress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01
  hosts:
    - console.back.pufferfish.ru
  tls:
    - secretName: minio-console-tls
      hosts:
        - console.back.pufferfish.ru

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01
  hosts:
    - minio.back.pufferfish.ru
  tls:
    - secretName: minio-tls
      hosts:
        - minio.back.pufferfish.ru
