replicaCount: 1
mode: standalone

auth:
  rootUser: ""
  rootPassword: ""

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 250m

consoleIngress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - minio.ui.pufferfish.ru           # 游댃 햊행햎햇햏햇햏: 햟햫혧혣햣 햠혦햩 minio.pufferfish.ru
  tls:
    - secretName: minio-ui-tls         # 游댃 햊행햎햇햏햇햏: 햟햫혧혣햣 햠혦햩 minio-tls
      hosts:
        - minio.ui.pufferfish.ru       # 游댃 햊행햎햇햏햇햏

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
  hosts:
    - minio.back.pufferfish.ru         # 游댃 햊행햎햇햏햇햏: 햟햫혧혣햣 햠혦햩 file.pufferfish.ru
  tls:
    - secretName: minio-back-tls       # 游댃 햊행햎햇햏햇햏: 햟햫혧혣햣 햠혦햩 file-tls
      hosts:
        - minio.back.pufferfish.ru     # 游댃 햊행햎햇햏햇햏
